exodata:  
  restart: on-failure:5
  image: teknologist/exo-data
mysqldata:  
  restart: on-failure:5
  image: teknologist/mysql-docker-data
mysql:  
  restart: on-failure:5
  image: mysql/mysql-server:latest
  environment:
    MYSQL_DATABASE: exo
    MYSQL_USER: exo
    MYSQL_PASSWORD: changeme
    MYSQL_ROOT_PASSWORD: changeme
  volumes_from:
  - mysqldata
exoplf:  
  restart: on-failure:5
  build: ./eXo/
  ports:
  - 4080:8080/tcp
  #image: teknologist/ubuntu-jdk7-exo-mysql
  environment:
    MYSQL_DATABASE: exo
    MYSQL_USER: exo
    MYSQL_PASSWORD: changeme
    LDAP_DNS: DC=mo,DC=example,DC=com 
    LDAP_HOST: ldap.example.com
    LDAP_PORT: 3268
    LDAP_ACCOUNT: ldap 
    LDAP_PASSWORD: changeme 
  links:
  - mysql
  volumes_from:
  - exodata
