exodata:  
  restart: on-failure:5
  image: teknologist/exo-data
mysqldata:  
  restart: on-failure:5
  image: teknologist/mysql-docker-data
mysql:  
  restart: on-failure:5
  image: mysql/mysql-server:latest
  environment:
    MYSQL_DATABASE: exo
    MYSQL_USER: exo
    MYSQL_PASSWORD: changeme
    MYSQL_ROOT_PASSWORD: changeme
  volumes_from:
  - mysqldata
exoplf:  
  restart: on-failure:5
  build: ./eXo/
  ports:
  - 4080:8080/tcp
  environment:
    MYSQL_DATABASE: exo
    MYSQL_USER: exo
    MYSQL_PASSWORD: changeme
    LDAP_DNS: DC=example,DC=com,DC=mo
    LDAP_HOST: dc.example.com.mo
    LDAP_PORT: 268
    LDAP_ACCOUNT: ldap
    LDAP_PASSWORD: changeme 
  links:
  - mysql
  volumes_from:
  - exodata
